name: flowhub_widgetbook
description: Widgetbook for FlowHub components.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: 3.15.0
  widgetbook_annotation: 3.6.0
  flutter_bloc: ^8.1.0
  mocktail: ^1.0.5
  flowhub:
    path: ../app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator: 3.11.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
